# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cssbundling-rails/all/cssbundling-rails.rbi
#
# cssbundling-rails-1.0.0

module Cssbundling
end
class Cssbundling::Engine < Rails::Engine
end
