# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/graphwerk/all/graphwerk.rbi
#
# graphwerk-1.2.1

module Graphwerk
  def self.for_application(**args); end
end
module Graphwerk::Constants
end
class Graphwerk::Layout < T::Enum
end
class Graphwerk::DeprecatedReferencesLoader
  def deprecated_references_file(*args, &blk); end
  def initialize(*args, &blk); end
  def load(*args, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Graphwerk::Presenters
end
class Graphwerk::Presenters::Package
  def color(*args, &blk); end
  def dependencies(*args, &blk); end
  def deprecated_references(*args, &blk); end
  def initialize(*args, &blk); end
  def name(*args, &blk); end
  def package_name(*args, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Graphwerk::Presenters::Package::Name
  def initialize(*args, &blk); end
  def node_name(*args, &blk); end
  def root?(*args, &blk); end
  def without_root_package(*args, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Graphwerk::Builders
end
class Graphwerk::Builders::Graph
  def add_package_dependencies_to_graph(*args, &blk); end
  def add_packages_to_graph(*args, &blk); end
  def build(*args, &blk); end
  def build_empty_graph(*args, &blk); end
  def build_empty_nodes(*args, &blk); end
  def draw_dependencies(*args, &blk); end
  def draw_deprecated_references(*args, &blk); end
  def initialize(*args, &blk); end
  def packages(*args, &blk); end
  def setup_graph(*args, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Graphwerk::Railtie < Rails::Railtie
end
