# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jsbundling-rails/all/jsbundling-rails.rbi
#
# jsbundling-rails-1.0.3

module Jsbundling
end
class Jsbundling::Engine < Rails::Engine
end
