# Turn on dependency checks for this package
enforce_dependencies: true

# Turn on privacy checks for this package
enforce_privacy: true

# A list of this package's dependencies
dependencies:
- components/app_base
- components/transactional_outbox
- components/user_access
